const categories = [
 {id:'service',icon:'$',title:'Service, Pricing & Estimates',desc:'First-hour labor, estimates, scheduling, price matching, and how LIFTX approaches cost.',questions:[
  ['How does the first hour of labor work?',`The first hour of labor begins when we arrive and is billed in full. Whether the visit takes 15 minutes or 55 minutes, the price does not increase unless the work continues into the next hour. Before additional work is performed, we explain what we found and discuss the available options.`],
  ['If I move forward with a repair or replacement, do I still pay the first hour?',`No. If an issue is identified and you choose to move forward with a qualifying repair or replacement supplied by LIFTX, the initial hour of labor is waived. Rather than paying separately for the service visit and the installation, that first hour is applied toward the work being performed.`],
  ['Can you give me an estimate over the phone?',`In many cases, yes. We provide minimum pricing or a general price range whenever possible so you have a realistic starting point. Photos or a short video can help us narrow down the issue and arrive better prepared. Some problems still require an on-site inspection. We would rather wait for the facts than make a promise based on an assumption.`],
  ['Why isn’t LIFTX always the lowest-priced option?',`Our pricing is intended to fall in the middle of the market: fair, competitive, and backed by experience, quality products, workmanship, and warranty coverage. Our background includes residential doors as well as highly technical commercial and high-speed systems. That same attention to safety and detail is applied to every job.`],
  ['Will LIFTX review or match a competitor’s written quote?',`Yes. If you have a legitimate written estimate for a comparable product, scope of work, and warranty, do not be afraid to ask. If we review it and believe our pricing is higher than it should be, we will gladly consider matching it.`],
  ['Will you tell me if a repair is not worth the money?',`Yes—every time. LIFTX does not upsell; we recommend. If a repair makes financial sense, we will say so. If replacement provides better long-term value, we will explain why. Our reputation is worth more than a single sale, and we will not waste your time or money.`]
 ]},
 {id:'repair',icon:'⚒',title:'Repairs & Safety',desc:'Broken springs, heavy doors, same-day repairs, inspections, and when a door should not be operated.',questions:[
  ['Can my garage door be repaired the same day?',`In many cases, yes. Depending on schedule volume and the parts required, most repairs can be completed the same day. If the correct part is not immediately available, we may be able to make the door safe or provide a temporary solution and return as soon as the proper part is available.`],
  ['Can I open my garage door if a spring is broken?',`No. Garage door springs counterbalance the weight of the door. When one breaks, the door can become dramatically heavier and dangerous to operate. On a two-spring system, the remaining spring cannot properly balance the door. On a single-spring system, the door may be left near its full weight. Trying to operate it can damage the opener, injure your back, or allow the door to fall. Stop using the door and have it inspected.`],
  ['Should both springs be replaced if only one is broken?',`Yes. LIFTX replaces both springs as a matched pair. Springs wear together over thousands of cycles. If one has reached the end of its service life, the other has usually experienced the same use and may have been placed under additional strain. Replacing both restores proper balance and allows the complete repair to be covered by the applicable manufacturer and LIFTX warranties.`],
  ['What if my garage door cannot be safely repaired?',`Most garage door problems are repairable. If a door is no longer structurally sound, cannot function reliably, or would remain unsafe after a proposed repair, we will say so. Anything we touch becomes our responsibility. Safety comes first, and we will not perform a repair we cannot confidently stand behind.`],
  ['My garage door is getting louder. What could be causing it?',`Garage door problems are often several small issues adding up rather than one isolated noise. If the sound has gradually changed, the opener may be one area to inspect, but rollers, hardware, balance, track, and lubrication can all contribute. We prefer to see the entire system rather than diagnose it from one sound over the phone.`],
  ['When should a heavy or struggling garage door be inspected?',`If the door feels unusually heavy, the opener struggles to lift it, or the door no longer operates the way it normally does, it is worth having someone look at it. Those changes can indicate a spring, balance, track, or hardware problem and can place unnecessary strain on the opener.`]
 ]},
 {id:'newdoors',icon:'▥',title:'New Garage Doors',desc:'Replacement decisions, insulation, lifespan, sections, tracks, hardware, and what comes with a new door.',questions:[
  ['How do I know if I need a new garage door?',`The first question is why you want it replaced. Is it unsafe, unreliable, structurally damaged, or are you looking for a new style or better performance? Our job is not to sell you something you can barely afford. It is to understand what you want, meet you within a realistic budget, and explain whether repair or replacement makes more sense.`],
  ['Should I choose an insulated garage door?',`It depends on the application, but in Idaho we generally recommend insulated doors for homes. We would not normally put an insulated door on a storage shed where temperature does not matter, and we would not recommend a non-insulated door for an attached home in the middle of an Idaho winter. The recommendation should match how the space is used.`],
  ['Can I replace only one damaged section?',`Sometimes. It depends on the manufacturer, collection, age, and whether a compatible section is still available. Door collections change, and replacement sections can become obsolete or incompatible even when they look similar. Send photos of the damaged area and any labels or stickers on the side of the sections. That may allow us to identify the door before scheduling a trip.`],
  ['Can I reuse my existing tracks and hardware with a new door?',`No. Every new garage door purchased through LIFTX includes new tracks, springs, and hardware designed for that system. We do not install new sections onto old tracks. A complete system protects operation, compatibility, safety, and warranty coverage and allows us to stand behind the finished installation.`],
  ['How long should a garage door last?',`There is no perfect answer. Quality, installation, usage, maintenance, environment, and warranty all matter. Under normal conditions and with proper maintenance, LIFTX expects the doors we sell and install to provide at least 15 years of reliable service. Many last longer, but no responsible company should guarantee one exact lifespan for every application.`],
  ['What is included with a new garage door from LIFTX?',`A new door comes as a complete system with new tracks, springs, and hardware. It also includes the applicable manufacturer warranties, the LIFTX one-year workmanship warranty, and a one-year maintenance plan with scheduled inspection and lubrication visits.`]
 ]},
 {id:'openers',icon:'⚙',title:'Garage Door Openers',desc:'Repair versus replacement, internal parts, existing openers, bundle pricing, and warranty limitations.',questions:[
  ['Can my garage door opener be repaired, or do I need a new one?',`LIFTX performs in-depth opener repairs and can source many internal parts. However, some internal repairs can approach the cost of a brand-new opener with a full manufacturer warranty, quieter operation, current safety features, and modern connectivity. We will explain both options and help you compare the actual value.`],
  ['Are internal opener repairs covered by the LIFTX workmanship warranty?',`No. Internal opener or operator repairs are not covered by the LIFTX workmanship warranty. Any manufacturer warranty offered on the replacement component may still apply. This limitation will be explained before the repair is approved.`],
  ['Do I need a new opener when I replace my garage door?',`Not necessarily. If the current opener works properly and is compatible with the new door, LIFTX will not pressure you to replace it. Customers who choose to replace both at the same time may qualify for bundle pricing, and modern openers are generally quieter and offer newer features.`],
  ['Why might replacing an opener be a better value than repairing it?',`A repair can make sense when the failed component is available and the remaining system is in good condition. Replacement may offer better value when the repair cost approaches the price of a complete new opener with a manufacturer warranty and updated features. We compare the options rather than automatically recommending one path.`]
 ]},
 {id:'maintenance',icon:'◷',title:'Maintenance & Warranty',desc:'Maintenance frequency, what is inspected, workmanship coverage, and how spring warranties differ.',questions:[
  ['How often should my garage door be serviced?',`It depends on usage. A heavily used residential or commercial door will need attention sooner than a door used occasionally. Most people wait until something fails, but changes in sound or operation are often a good reason to schedule an inspection.`],
  ['What is checked during a maintenance visit?',`We visually inspect components that support the structure of the door or operate under tension, check door level and balance, inspect the track for level and plumb, review operating hardware, and lubricate the appropriate components.`],
  ['What maintenance is included with a new LIFTX installation?',`New LIFTX installations include a one-year maintenance plan alongside the workmanship warranty. The plan provides one maintenance visit every three months during the first year.`],
  ['Why do garage door springs have different warranties?',`Spring warranties are tied to cycle rating and expected service life. Lower-cycle springs generally carry shorter warranties, while higher-cycle springs are designed for more open-and-close cycles and carry longer warranties. The right option depends on usage, budget, and how long you want the repair to last.`],
  ['Why does warranty coverage matter when comparing prices?',`Two estimates are not truly comparable unless the products, scope of work, and warranty coverage are comparable. Lower pricing may come with shorter product life, fewer included components, or less coverage. LIFTX pricing includes the warranties stated in the estimate so customers can compare the complete value, not only the bottom-line number.`]
 ]},
 {id:'products',icon:'✓',title:'Products & Installation Standards',desc:'Customer-supplied parts, complete systems, product accountability, and how LIFTX avoids loose ends.',questions:[
  ['Can I supply my own garage door or parts?',`Typically, no. In limited circumstances, LIFTX may install a new door purchased by the homeowner, but customer-supplied products can create compatibility and warranty complications. We recommend purchasing through LIFTX so we can manage the project from start to finish, take full accountability, and resolve problems without loose ends.`],
  ['Why does LIFTX prefer to supply the complete door system?',`When LIFTX supplies the door, tracks, springs, hardware, and related components, we know the parts are compatible and can take full responsibility for the finished installation. If something is wrong, there is one accountable company handling it rather than a dispute between the seller, manufacturer, and installer.`],
  ['Does every new door include new springs and hardware?',`Yes. New doors purchased through LIFTX come standard with the matching tracks, springs, and hardware package. We do not separate the sections from the system they were designed to operate with.`]
 ]},
 {id:'commercial',icon:'▦',title:'Commercial, Builders & Contractors',desc:'Commercial systems, technical experience, bidding, scheduling, and complete project accountability.',questions:[
  ['Does LIFTX work on commercial and high-speed door systems?',`Yes. LIFTX experience includes residential sectional doors as well as commercial, industrial, and highly technical high-speed door systems. That background informs how we approach safety, diagnostics, controls, installation, and long-term reliability across every type of door.`],
  ['Why does high-speed door experience matter on a standard garage door?',`High-speed systems are more technical and less forgiving than a typical sectional door. They require precise mechanical, electrical, and safety work. That experience carries over into residential and commercial sectional work through stronger diagnostics, attention to detail, and an understanding of how complete door systems interact.`],
  ['Does LIFTX work with builders and contractors?',`Yes. LIFTX works with builders, contractors, property managers, and commercial clients on new construction, replacement, multi-door packages, specialty systems, scheduling, and project coordination.`],
  ['Can LIFTX coordinate product selection and installation from start to finish?',`Yes. That is the preferred approach. By managing product selection, ordering, compatibility, delivery, installation, warranty, and follow-up, LIFTX can take full accountability and reduce loose ends for the customer, builder, or project manager.`]
 ]}
];

const grid=document.querySelector('#category-grid'), home=document.querySelector('#category-home'), view=document.querySelector('#category-view'), searchResults=document.querySelector('#search-results');
const list=document.querySelector('#accordion-list'), resultList=document.querySelector('#result-list'), title=document.querySelector('#category-title'), desc=document.querySelector('#category-description');
const search=document.querySelector('#faq-search'), clear=document.querySelector('#clear-search');

function card(c){const b=document.createElement('button');b.className='category-card';b.innerHTML=`<span class="category-icon">${c.icon}</span><span><h3>${c.title}</h3><p>${c.desc}</p></span><span class="arrow">→</span>`;b.onclick=()=>showCategory(c.id);return b}
categories.forEach(c=>grid.appendChild(card(c)));
function faqItem(q,a){const wrap=document.createElement('div');wrap.className='faq-item';wrap.innerHTML=`<button class="faq-question" aria-expanded="false"><span>${q}</span><span class="plus">+</span></button><div class="faq-answer"><p>${a}</p></div>`;const btn=wrap.querySelector('button');btn.onclick=()=>{wrap.classList.toggle('open');btn.setAttribute('aria-expanded',wrap.classList.contains('open'))};return wrap}
function showCategory(id){const c=categories.find(x=>x.id===id);if(!c)return;search.value='';clear.hidden=true;home.hidden=true;searchResults.hidden=true;view.hidden=false;title.textContent=c.title;desc.textContent=c.desc;list.innerHTML='';c.questions.forEach(([q,a])=>list.appendChild(faqItem(q,a)));location.hash=id;window.scrollTo({top:document.querySelector('.faq-shell').offsetTop-70,behavior:'smooth'})}
document.querySelector('#back-button').onclick=()=>{view.hidden=true;searchResults.hidden=true;home.hidden=false;history.replaceState(null,'','#home');window.scrollTo({top:document.querySelector('.faq-shell').offsetTop-70,behavior:'smooth'})};
function doSearch(){const term=search.value.trim().toLowerCase();clear.hidden=!term;if(!term){searchResults.hidden=true;view.hidden=true;home.hidden=false;return} const found=[];categories.forEach(c=>c.questions.forEach(([q,a])=>{if((q+' '+a).toLowerCase().includes(term))found.push([q,a,c.title])}));home.hidden=true;view.hidden=true;searchResults.hidden=false;resultList.innerHTML='';document.querySelector('#result-count').textContent=`${found.length} result${found.length===1?'':'s'} across all categories.`;found.forEach(([q,a,c])=>{const item=faqItem(q,`<strong>${c}</strong><br><br>${a}`);resultList.appendChild(item)})}
search.addEventListener('input',doSearch);clear.onclick=()=>{search.value='';doSearch();search.focus()};
const menuBtn=document.querySelector('.menu-button'), menu=document.querySelector('.mobile-menu');menuBtn.onclick=()=>{const open=menu.hasAttribute('hidden');if(open)menu.removeAttribute('hidden');else menu.setAttribute('hidden','');menuBtn.setAttribute('aria-expanded',open)};
const hash=location.hash.slice(1);if(categories.some(c=>c.id===hash))showCategory(hash);
